# Generated by Django 5.0.3 on 2024-06-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='supplier',
        ),
    ]
