# Generated by Django 5.0.3 on 2024-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_manufacturer_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='dic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='ico',
            field=models.CharField(max_length=100),
        ),
    ]
