# Generated by Django 5.0.3 on 2024-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_manufacturer_dic_alter_manufacturer_ico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='dic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ico',
            field=models.CharField(max_length=20),
        ),
    ]
