# Generated by Django 5.0.3 on 2024-06-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_supplier_dic_alter_supplier_ico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
