# Generated by Django 5.0.3 on 2024-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_remove_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.CharField(default='Datum objednání', max_length=100),
        ),
    ]
