# Generated by Django 5.0.3 on 2024-07-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_supplierset_delete_productsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer'),
        ),
        migrations.AlterField(
            model_name='supplierset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
        ),
    ]
