# Generated by Django 5.0.3 on 2024-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_name_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='order_number',
        ),
    ]
