# Generated by Django 5.0.3 on 2024-07-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_store_remove_product_stock_number_productstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_number',
            field=models.CharField(default='Centrální sklad', max_length=100),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store')),
            ],
            options={
                'index_together': {('product',)},
            },
        ),
        migrations.DeleteModel(
            name='ProductStore',
        ),
    ]
