# Generated by Django 5.0.3 on 2024-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_tablehead_status_tablehead_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_location',
            field=models.CharField(default='Centrální sklad', max_length=100),
        ),
    ]
