# Generated by Django 5.0.3 on 2024-07-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_number',
        ),
        migrations.RemoveField(
            model_name='tablehead',
            name='stock_number',
        ),
    ]
