# Generated by Django 5.0.3 on 2024-04-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablehead',
            name='is_delivered',
            field=models.CharField(default='Dodáno', max_length=100),
        ),
    ]
