# Generated by Django 5.0.3 on 2024-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_order_name_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Název položky', max_length=100),
        ),
    ]
