# Generated by Django 5.0.3 on 2024-05-31 09:20
from django.db import migrations


def assign_created_by(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    default_user = User.objects.get(username='npgroup-admin')
    Product = apps.get_model('core', 'Product')
    products_without_created_by = Product.objects.filter(created_by__isnull=True)
    for product in products_without_created_by:
        product.created_by = default_user
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tablehead_created_by_product_created_by'),
    ]

    operations = [
        migrations.RunPython(assign_created_by),
    ]
