# Generated by Django 5.0.3 on 2024-05-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order',)},
        ),
        migrations.AlterIndexTogether(
            name='orderitem',
            index_together={('order',)},
        ),
    ]
