# Generated by Django 5.0.3 on 2024-05-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
