# Generated by Django 5.0.3 on 2024-05-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.CharField(default='Název položky', max_length=100),
        ),
    ]
