# Generated by Django 5.0.3 on 2024-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablehead',
            name='address',
            field=models.CharField(default='Adresa', max_length=100),
        ),
        migrations.AddField(
            model_name='tablehead',
            name='bank_account',
            field=models.CharField(default='Bank. účet', max_length=100),
        ),
        migrations.AddField(
            model_name='tablehead',
            name='company',
            field=models.CharField(default='Firma', max_length=100),
        ),
        migrations.AddField(
            model_name='tablehead',
            name='contact',
            field=models.CharField(default='Kontakt', max_length=100),
        ),
        migrations.AddField(
            model_name='tablehead',
            name='div',
            field=models.CharField(default='DIČ', max_length=100),
        ),
        migrations.AddField(
            model_name='tablehead',
            name='ico',
            field=models.CharField(default='IČO', max_length=100),
        ),
    ]
