# Generated by Django 5.0.3 on 2024-06-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_tablehead_address_tablehead_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablehead',
            old_name='div',
            new_name='dic',
        ),
    ]
