# Generated by Django 5.0.3 on 2024-05-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_orderitem_name_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('ks', 'ks'), ('bal.', 'bal.'), ('ml', 'ml'), ('l', 'l')], default='ks', max_length=10),
        ),
    ]
