# Generated by Django 5.0.3 on 2024-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_div_tablehead_dic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.AddField(
            model_name='supplier',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='dic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
