# Generated by Django 5.0.3 on 2024-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_supplier_contact_supplier_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
