# Generated by Django 5.0.3 on 2024-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Název', max_length=100)),
                ('stock_number', models.CharField(default='Číslo skladu', max_length=100)),
                ('order_number', models.CharField(default='Číslo obj.', max_length=100)),
                ('quantity', models.CharField(default='Množství', max_length=100)),
                ('min_quantity', models.CharField(default='Min. množství', max_length=100)),
                ('expiration_date', models.CharField(default='Expirace', max_length=100)),
                ('supplier', models.CharField(default='Dodavatel', max_length=100)),
                ('status', models.CharField(default='Status', max_length=100)),
                ('order_date', models.CharField(default='Datum objednání', max_length=100)),
                ('delivery_date', models.CharField(default='Datum dodání', max_length=100)),
            ],
        ),
    ]
