# Generated by Django 5.0.3 on 2024-03-24 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tablehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], default='green', max_length=20)),
                ('product_type', models.CharField(choices=[('Materiál', 'Materiál'), ('Nástroj', 'Nástroj'), ('Zařízení', 'Zařízení')], default='material', max_length=20)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
