# Generated by Django 5.0.3 on 2024-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Materiál', 'Materiál'), ('Nástroj', 'Nástroj'), ('Zařízení', 'Zařízení')], default='Materiál', max_length=20),
        ),
    ]
